date = '2020-01-16'
tags = [
  'funding',
  'USA',
]
author = 'Dan Katz'
url = 'https://www.nitrd.gov/nitrdgroups/images/6/65/HEC-Daniel-Katz-01162020.pdf'
text = '"~20% of the overall NSF research budget" include software in their project abstract.'
