date = '2020-01-16'
authors = [
  {  'name': 'Daniel S. Katz',
     'orcid': '0000-0001-5934-7525',
  },
]
title = 'Research Software Sustainability'
url = 'https://www.nitrd.gov/nitrdgroups/images/6/65/HEC-Daniel-Katz-01162020.pdf'
mentions = [
  {'tags': ['funding', 'USA'],
   'text': '"~20% of the overall NSF research budget" include software in their project abstract.',
  },
]
